version: '3'

services:
  php:
    image: php:7.4.8-apache
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./view:/var/www/html
    ports:
      - 8888:80
    build:
      context: .
      dockerfile: ./Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  php-mecab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./view:/app
    tty: true
