version: '3'

services:
  php:
    image: php:7.4.8-fpm
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./view:/var/www/html
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: ./Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
    depends_on:
      - php-mecab
    networks:
      - app-network
  php-mecab:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      - ./view:/app
    tty: true

networks:
  app-network:
    driver: bridge
